### PR TITLE
fix: add a back button on HikeDetails and RunHike loading screen

### LINKED ISSUE #299: Fix: offline mode MapScreen -> HikeDetailScreen
Paths to recreate it:
1. Online search for hikes.
2. Disable your internet connection.
3. Try to go to the HikeDetailsScreen of a Hike.
4. There is no back button to go back.

So the user should have the option to go back in this case with the Back Button.

### PR DESCRIPTION
**Pull request by Wylwi**
# Summary

- This fixes #299 where a user could be stuck in a soft loop in case their internet was not working, while trying to go on the HikeDetails screen.
- This does the same thing on the RunHikeScreen, even though the bug should never happen here since we already have the details

# Details
Paths to recreate the bug:

- Online search for hikes.
- Disable your internet connection.
- Try to go to the HikeDetailsScreen of a Hike.
- User is stuck

This now adds a BackButton for the user to escape.

# Old UI

Screenshot_20241217_165010
Screenshot_20241217_165016

# New UI

Screenshot_20241217_164650
Screenshot_20241217_164708

### CODE REVIEW

File: app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt [hunk 1]
```diff
@@ -37,58 +47,73 @@ fun WithDetailedHike(
...
-    // All the details of the hike have been computed, pass them on to the content callback
-    hike.isFullyLoaded() -> {
-      val detailedHike =
-          try {
-            hike.withDetailsOrThrow()
-          } catch (e: Exception) {
-            Log.d(WithDetailedHike.LOG_TAG, "Error while getting detailed hike: $e")
-            null
-          }
+  var detailedHike: DetailedHike? by remember { mutableStateOf(null) }
```
Comment (rBergCode) [inline app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt:56]: Question: Why do you need this variable? It seems it could work without it

File: app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt [hunk 2]
```diff
@@ -37,58 +47,73 @@ fun WithDetailedHike(
...
 
-      if (detailedHike != null) {
-        withDetailedHike(detailedHike)
-      } else {
-        whenError()
-      }
+  Column(Modifier.fillMaxSize().safeDrawingPadding()) {
+    if (detailedHike == null && !hike.isFullyLoaded()) {
```
Comment (rBergCode) [inline app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt:59]: Same here, I think you only need the second condition

**Review by rBergCode — CHANGES_REQUESTED** [review]
Nice fix! I have a small question and you will be good to go!

File: app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt (hunk 1 above)
Comment (Wylwi) [reply app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt]: Yep, it works without it

File: app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt (hunk 2 above)
Comment (Wylwi) [reply app/src/main/java/ch/hikemate/app/ui/components/WithDetailedHike.kt]: Yep, it works without it

**Review by rBergCode — APPROVED** [review]
Thanks for the changes!
